[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/"
  to = "/app/"
  status = 302

[[redirects]]
  from = "/app/*"
  to = "/app/index.html"
  status = 200

[[headers]]
  for = "/app/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
